### ISSUE TITLE
Error: Evaluation failed

### ISSUE THREAD

**Issue by jbreitbart** [Burnett01/actions-drawio#1]
I am trying to use your github action, but I get the following error message. Do you have any idea what may be causing this?

```
Run Burnett01/actions-drawio@1.0
  with:
    src: string.drawio
    dest: string.png
    quality: 100
    scale: 1.0
/usr/bin/docker run --name e40afc7dddc95e4da3897cc7191dbd3b99_d81059 --label 5588e4 --workdir /github/workspace --rm -e INPUT_SRC -e INPUT_DEST -e INPUT_QUALITY -e INPUT_SCALE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/asciidoctor-action/asciidoctor-action":"/github/workspace" 5588e4:0afc7dddc95e4da3897cc7191dbd3b99
Error: Evaluation failed: 
    at ExecutionContext._evaluateInternal (/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async /drawio-batch.js:75:5
  -- ASYNC --
    at ExecutionContext.<anonymous> (/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  -- ASYNC --
    at Frame.<anonymous> (/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/node_modules/puppeteer/lib/Page.js:833:43)
    at Page.<anonymous> (/node_modules/puppeteer/lib/helper.js:112:23)
    at /drawio-batch.js:75:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by Burnett01** [comment]
@jbreitbart Hey, I just tested this action again and I couldn't re-produce your issue.
I can't really tell if this is related to the underlaying operating system that is running this action.
For instance, I'm using  `runs-on: ubuntu-latest` in my workflow file, see here: https://github.com/Burnett01/actions-drawio/actions/runs/726058121

Which operating system did you use?

**Comment by mielvds** [comment]
I have the same issue: https://github.com/ErfgoedPod/orchestrator/runs/2468034484?check_suite_focus=true

**Comment by Burnett01** [comment]
> I have the same issue: https://github.com/ErfgoedPod/orchestrator/runs/2468034484?check_suite_focus=true

Thank you very much for your post! I was able to re-produce your issue when using the same drawio XML that you've used in your actions. Tomorrow I will take a closer look as to why it is failing. This might be related to the XML document. Keeping you posted, greetings Steve

**Comment by mielvds** [comment]
Great, thanks!

**Comment by Burnett01** [comment]
After a lot of testing, I found the issue.
The underlaying drawio-batch nodeJS module only supports drawio XML documents that are compressed.
Uncompressed XML documents are not supported.

At first I imported your drawio XML into the editor and exported it as uncompressed XML and the action failed.
Then I exported it as compressed and it worked:  

https://github.com/Burnett01/actions-drawio/actions/runs/800518408  (See the artifacts)

Please make sure your document is compressed before supplying it to the action.
You can do so by setting the Page property to "compressed" or when exporting the document as XML.

![2021-04-30 21_49_08-test3 xml - diagrams net](https://user-images.githubusercontent.com/1208707/116747317-feb49680-a9fd-11eb-8064-6e760c543d0d.png)

![2021-04-30 21_47_05-test3 xml - diagrams net](https://user-images.githubusercontent.com/1208707/116747331-04aa7780-a9fe-11eb-89a1-5a80aea018f5.png)

![2021-04-30 21_51_10-test3 xml - diagrams net](https://user-images.githubusercontent.com/1208707/116747495-49cea980-a9fe-11eb-9738-6a524d6d2d89.png)

![2021-04-30 21_47_17-test3 xml - diagrams net](https://user-images.githubusercontent.com/1208707/116747349-0a07c200-a9fe-11eb-835b-1aa6036f47d0.png)

I will make sure to warn the users about that in the README of the action and the docker image.

I hope this helps, greetings Steven

CC: @mielvds @jbreitbart
